#!/bin/bash

#Script: Ops 201 Class 03 Ops Challenge Solution
#Author: Quin Garner
# Date of latest revision: 4/26/23
# Purpose: Print a string to the terminal
# Main

sudo last /var/log/wtmp

echo "this is the login history."


sudo last -3

# End